// Car identity: ordinal -> name/year/make/model. Loaded from the slim DB
// (public/cars.json, generated by scripts/build-car-db.mjs). Names were
// auto-generated from game asset names — best-effort labels.

export interface CarInfo {
  ordinal: number;
  name: string; // "1969 Toyota 2000GT"
  year: number;
  make: string;
  model: string;
}

interface SlimEntry {
  n: string;
  y: number;
  mk: string;
  md: string;
}

let db: Map<number, CarInfo> | null = null;
let loading: Promise<void> | null = null;
const listeners = new Set<() => void>();

export function carDbReady(): boolean {
  return db != null;
}

/** Kick off (or join) the one-time fetch; notifies subscribers when loaded. */
export function loadCarDb(): Promise<void> {
  if (db) return Promise.resolve();
  if (!loading) {
    loading = fetch(`${import.meta.env.BASE_URL}cars.json`)
      .then((r) => {
        if (!r.ok) throw new Error(`cars.json: HTTP ${r.status}`);
        return r.json() as Promise<Record<string, SlimEntry>>;
      })
      .then((raw) => {
        const m = new Map<number, CarInfo>();
        for (const [k, v] of Object.entries(raw)) {
          const ordinal = Number(k);
          m.set(ordinal, { ordinal, name: v.n, year: v.y, make: v.mk, model: v.md });
        }
        db = m;
        for (const fn of listeners) fn();
      })
      .catch((e) => {
        loading = null; // allow retry on next call
        throw e;
      });
  }
  return loading;
}

export function onCarDbLoaded(fn: () => void): () => void {
  listeners.add(fn);
  return () => listeners.delete(fn);
}

export function carInfo(ordinal: number): CarInfo | null {
  return db?.get(ordinal) ?? null;
}

/** Display name with a graceful fallback for ordinals not in the DB. */
export function carName(ordinal: number): string {
  return carInfo(ordinal)?.name ?? `Unknown car (#${ordinal})`;
}

export function allCars(): CarInfo[] {
  return db ? [...db.values()] : [];
}

/** Case-insensitive search over year/make/model/name; every term must match. */
export function searchCars(query: string): CarInfo[] {
  const terms = query.toLowerCase().split(/\s+/).filter(Boolean);
  const cars = allCars();
  if (terms.length === 0) return cars;
  return cars.filter((c) => {
    const hay = `${c.year} ${c.name}`.toLowerCase();
    return terms.every((t) => hay.includes(t));
  });
}

// Forza Horizon PI class index -> letter (telemetry car.class).
const CLASSES = ["D", "C", "B", "A", "S1", "S2", "X"];
export function classLetter(cls: number): string {
  return CLASSES[cls] ?? "?";
}

/** "A 800" style build label from telemetry class/pi. */
export function classLabel(cls: number, pi: number): string {
  return `${classLetter(cls)} ${pi}`;
}
